/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface AuthResponseDTO {
  token?: string;
  refreshToken?: string;
  userId?: number;
  username?: string;
}
