/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ConnectionResponseDTOStatus } from './connectionResponseDTOStatus';

export interface ConnectionResponseDTO {
  id?: number;
  requesterUsername?: string;
  receiverUsername?: string;
  status?: ConnectionResponseDTOStatus;
  createdAt?: string;
}
