/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserResponseDTO } from './userResponseDTO';
import type { ConnectionResponseDTOStatus } from './connectionResponseDTOStatus';

export interface ConnectionResponseDTO {
  id?: number;
  otherUser?: UserResponseDTO;
  status?: ConnectionResponseDTOStatus;
  initiatedByMe?: boolean;
  createdAt?: string;
}
