/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ConnectionResponseDTOStatus = typeof ConnectionResponseDTOStatus[keyof typeof ConnectionResponseDTOStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConnectionResponseDTOStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
} as const;
