/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ConnectionRequestDTO {
  requesterId?: number;
  receiverId?: number;
}
