/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { HobbyRequestDTO } from "./hobbyRequestDTO";

export type CreateHobbyBody = {
  hobbyRequestDto?: HobbyRequestDTO;
  image?: Blob;
};
