/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface HobbySummary {
  hobbyName?: string;
  xpGained?: number;
  logsCount?: number;
  currentStreak?: number;
  longestStreak?: number;
  currentLevel?: number;
  goalsCompleted?: string[];
}
