/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Data } from './data';
import type { HobbyLogResponseDTO } from './hobbyLogResponseDTO';

export interface HobbyResponseDTO {
  id?: number;
  name?: string;
  description?: string;
  totalXp?: number;
  level?: number;
  createdAt?: Data;
  currentStreak?: number;
  longestStreak?: number;
  logs?: HobbyLogResponseDTO[];
}
