/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface HobbyLogResponseDTO {
  id?: number;
  date?: string;
  durationMinutes?: number;
  description?: string;
  effortLevel?: number;
  mood?: string;
  xpEarned?: number;
  hobbyId?: number;
  leveledUp?: boolean;
}
