/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface HobbyLogResponseDTO {
  id?: number;
  date?: string;
  description?: string;
  xpEarned?: number;
  hobbyId?: number;
  completedGoals?: string[];
  message?: string;
  levelsProgressed?: number;
  // Updated hobby state for instant level-up sync
  updatedTotalXp?: number;
  updatedXpNeededToLevelUp?: number;
  updatedLevel?: number;
}
