/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { HobbyLogResponseDTO } from './hobbyLogResponseDTO';

export interface HobbyResponseDTO {
  id?: number;
  name?: string;
  totalXp?: number;
  level?: number;
  createdAt?: string;
  currentStreak?: number;
  longestStreak?: number;
  logs?: HobbyLogResponseDTO[];
  goals?: string[];
  hobbyImage?: string;
  habits?: string[];
}
