/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { HobbySummary } from "./hobbySummary";

export interface InsightDTO {
  weeklySummary?: string;
  totalXpGained?: number;
  totalLogsCount?: number;
  hobbySummaries?: HobbySummary[];
  advice?: string;
  compliment?: string;
  highlights?: string[];
  weekStartDate?: string;
  weekEndDate?: string;
  generatedAt?: string;
}
