/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { HobbyResponseDTO } from './hobbyResponseDTO';

export interface UserResponseDTO {
  id?: number;
  username?: string;
  email?: string;
  profilePhoto?: string;
  hobbies?: HobbyResponseDTO[];
}
