/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UserRequestDTO {
  username?: string;
  email?: string;
  password?: string;
}
