/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AuthResponseDTO,
  LoginRequest,
  RegisterBody
} from '../../models/api';





  export const register = <TData = AxiosResponse<AuthResponseDTO>>(
    registerBody: RegisterBody, options?: AxiosRequestConfig
 ): Promise<TData> => {const formData = new FormData();
formData.append(`user`, registerBody.user)
if(registerBody.profilePhoto !== undefined) {
 formData.append(`profilePhoto`, registerBody.profilePhoto)
 }

    return axios.post(
      `/api/auth/register`,
      formData,options
    );
  }
export const login = <TData = AxiosResponse<AuthResponseDTO>>(
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/auth/login`,
      loginRequest,options
    );
  }
export type RegisterResult = AxiosResponse<AuthResponseDTO>
export type LoginResult = AxiosResponse<AuthResponseDTO>
