/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  AuthResponseDTO,
  LoginRequest,
  RegisterBody
} from '../../models/api';

import { axiosInstance } from '../../lib/axios';




  export const register = (
    registerBody: RegisterBody,
 ) => {const formData = new FormData();
formData.append(`user`, registerBody.user)
if(registerBody.profilePhoto !== undefined) {
 formData.append(`profilePhoto`, registerBody.profilePhoto)
 }

      return axiosInstance<AuthResponseDTO>(
      {url: `/api/auth/register`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
      );
    }
  export const login = (
    loginRequest: LoginRequest,
 ) => {
      return axiosInstance<AuthResponseDTO>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest
    },
      );
    }
  export type RegisterResult = NonNullable<Awaited<ReturnType<typeof register>>>
export type LoginResult = NonNullable<Awaited<ReturnType<typeof login>>>
