/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  HobbyLogRequestDTO,
  HobbyLogResponseDTO
} from '../../models/api';

import { axiosInstance } from '../../lib/axios';




  export const createLog = (
    hobbyLogRequestDTO: HobbyLogRequestDTO,
 ) => {
      return axiosInstance<HobbyLogResponseDTO>(
      {url: `/api/hobby-logs`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: hobbyLogRequestDTO
    },
      );
    }
  export const getLogsByUser = (
    userId: number,
 ) => {
      return axiosInstance<HobbyLogResponseDTO[]>(
      {url: `/api/hobby-logs/user/${userId}`, method: 'GET'
    },
      );
    }
  export const deleteLog = (
    id: number,
 ) => {
      return axiosInstance<null>(
      {url: `/api/hobby-logs/${id}`, method: 'DELETE'
    },
      );
    }
  export type CreateLogResult = NonNullable<Awaited<ReturnType<typeof createLog>>>
export type GetLogsByUserResult = NonNullable<Awaited<ReturnType<typeof getLogsByUser>>>
export type DeleteLogResult = NonNullable<Awaited<ReturnType<typeof deleteLog>>>
