/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  HobbyRequestDTO,
  HobbyResponseDTO
} from '../../models/api';





  export const updateHobby = <TData = AxiosResponse<HobbyResponseDTO>>(
    id: number,
    hobbyRequestDTO: HobbyRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/hobbies/${id}`,
      hobbyRequestDTO,options
    );
  }
export const deleteHobby = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/hobbies/${id}`,options
    );
  }
export const createHobby = <TData = AxiosResponse<HobbyResponseDTO>>(
    hobbyRequestDTO: HobbyRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/hobbies`,
      hobbyRequestDTO,options
    );
  }
export const getHobbyById = <TData = AxiosResponse<HobbyResponseDTO>>(
    hobbyId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/hobbies/${hobbyId}`,options
    );
  }
export const getAllHobbies = <TData = AxiosResponse<HobbyResponseDTO[]>>(
    userId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/hobbies/all/${userId}`,options
    );
  }
export type UpdateHobbyResult = AxiosResponse<HobbyResponseDTO>
export type DeleteHobbyResult = AxiosResponse<void>
export type CreateHobbyResult = AxiosResponse<HobbyResponseDTO>
export type GetHobbyByIdResult = AxiosResponse<HobbyResponseDTO>
export type GetAllHobbiesResult = AxiosResponse<HobbyResponseDTO[]>
