/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  HobbyLogRequestDTO,
  HobbyLogResponseDTO
} from '../../models/api';





  export const createLog = <TData = AxiosResponse<HobbyLogResponseDTO>>(
    hobbyLogRequestDTO: HobbyLogRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/hobby-logs`,
      hobbyLogRequestDTO,options
    );
  }
export const getLogsByHobbyId = <TData = AxiosResponse<HobbyLogResponseDTO[]>>(
    hobbyId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/hobby-logs/${hobbyId}`,options
    );
  }
export const getLogsByUser = <TData = AxiosResponse<HobbyLogResponseDTO[]>>(
    userId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/hobby-logs/user/${userId}`,options
    );
  }
export const deleteLog = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/hobby-logs/${id}`,options
    );
  }
export type CreateLogResult = AxiosResponse<HobbyLogResponseDTO>
export type GetLogsByHobbyIdResult = AxiosResponse<HobbyLogResponseDTO[]>
export type GetLogsByUserResult = AxiosResponse<HobbyLogResponseDTO[]>
export type DeleteLogResult = AxiosResponse<void>
