/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateHobbyBody,
  HobbyResponseDTO
} from '../../models/api';





  export const addHabit = <TData = AxiosResponse<HobbyResponseDTO>>(
    hobbyId: number,
    addHabitBody: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/hobbies/add-habit/${hobbyId}`,
      addHabitBody,options
    );
  }
export const addGoal = <TData = AxiosResponse<HobbyResponseDTO>>(
    hobbyId: number,
    addGoalBody: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/hobbies/add-goal/${hobbyId}`,
      addGoalBody,options
    );
  }
export const createHobby = <TData = AxiosResponse<HobbyResponseDTO>>(
    createHobbyBody: CreateHobbyBody, options?: AxiosRequestConfig
 ): Promise<TData> => {const formData = new FormData();
if(createHobbyBody.hobbyRequestDto !== undefined) {
 formData.append(`hobbyRequestDto`, JSON.stringify(createHobbyBody.hobbyRequestDto));
 }
if(createHobbyBody.image !== undefined) {
 formData.append(`image`, createHobbyBody.image)
 }

    return axios.post(
      `/api/hobbies`,
      formData,options
    );
  }
export const getHobbyById = <TData = AxiosResponse<HobbyResponseDTO>>(
    hobbyId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/hobbies/${hobbyId}`,options
    );
  }
export const helloWorld = <TData = AxiosResponse<string>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/hobbies/test`,{
        responseType: 'text',
    ...options,}
    );
  }
export const getAllHobbies = <TData = AxiosResponse<HobbyResponseDTO[]>>(
    userId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/hobbies/all/${userId}`,options
    );
  }
export const deleteHobby = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/hobbies/${id}`,options
    );
  }
export type AddHabitResult = AxiosResponse<HobbyResponseDTO>
export type AddGoalResult = AxiosResponse<HobbyResponseDTO>
export type CreateHobbyResult = AxiosResponse<HobbyResponseDTO>
export type GetHobbyByIdResult = AxiosResponse<HobbyResponseDTO>
export type HelloWorldResult = AxiosResponse<string>
export type GetAllHobbiesResult = AxiosResponse<HobbyResponseDTO[]>
export type DeleteHobbyResult = AxiosResponse<void>
