/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  HobbyRequestDTO,
  HobbyResponseDTO
} from '../../models/api';

import { axiosInstance } from '../../lib/axios';




  export const updateHobby = (
    id: number,
    hobbyRequestDTO: HobbyRequestDTO,
 ) => {
      return axiosInstance<HobbyResponseDTO>(
      {url: `/api/hobbies/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: hobbyRequestDTO
    },
      );
    }
  export const deleteHobby = (
    id: number,
 ) => {
      return axiosInstance<null>(
      {url: `/api/hobbies/${id}`, method: 'DELETE'
    },
      );
    }
  export const createHobby = (
    hobbyRequestDTO: HobbyRequestDTO,
 ) => {
      return axiosInstance<HobbyResponseDTO>(
      {url: `/api/hobbies`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: hobbyRequestDTO
    },
      );
    }
  export const getHobbyById = (
    hobbyId: number,
 ) => {
      return axiosInstance<HobbyResponseDTO>(
      {url: `/api/hobbies/${hobbyId}`, method: 'GET'
    },
      );
    }
  export const getAllHobbies = (
    userId: number,
 ) => {
      return axiosInstance<HobbyResponseDTO[]>(
      {url: `/api/hobbies/all/${userId}`, method: 'GET'
    },
      );
    }
  export type UpdateHobbyResult = NonNullable<Awaited<ReturnType<typeof updateHobby>>>
export type DeleteHobbyResult = NonNullable<Awaited<ReturnType<typeof deleteHobby>>>
export type CreateHobbyResult = NonNullable<Awaited<ReturnType<typeof createHobby>>>
export type GetHobbyByIdResult = NonNullable<Awaited<ReturnType<typeof getHobbyById>>>
export type GetAllHobbiesResult = NonNullable<Awaited<ReturnType<typeof getAllHobbies>>>
