/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  SearchUsersParams,
  UserRequestDTO,
  UserResponseDTO
} from '../../models/api';





  export const getUser = <TData = AxiosResponse<UserResponseDTO>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/users/${id}`,options
    );
  }
export const updateUser = <TData = AxiosResponse<UserResponseDTO>>(
    id: number,
    userRequestDTO: UserRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/users/${id}`,
      userRequestDTO,options
    );
  }
export const getUserByUsername = <TData = AxiosResponse<UserResponseDTO>>(
    username: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/users/username/${username}`,options
    );
  }
export const searchUsers = <TData = AxiosResponse<UserResponseDTO[]>>(
    params: SearchUsersParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/users/search`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
export type GetUserResult = AxiosResponse<UserResponseDTO>
export type UpdateUserResult = AxiosResponse<UserResponseDTO>
export type GetUserByUsernameResult = AxiosResponse<UserResponseDTO>
export type SearchUsersResult = AxiosResponse<UserResponseDTO[]>
