/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  UserRequestDTO,
  UserResponseDTO
} from '../../models/api';

import { axiosInstance } from '../../lib/axios';




  export const getUser = (
    id: number,
 ) => {
      return axiosInstance<UserResponseDTO>(
      {url: `/api/users/${id}`, method: 'GET'
    },
      );
    }
  export const updateUser = (
    id: number,
    userRequestDTO: UserRequestDTO,
 ) => {
      return axiosInstance<UserResponseDTO>(
      {url: `/api/users/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: userRequestDTO
    },
      );
    }
  export type GetUserResult = NonNullable<Awaited<ReturnType<typeof getUser>>>
export type UpdateUserResult = NonNullable<Awaited<ReturnType<typeof updateUser>>>
